### ISSUE TITLE
Minimal amount annotations?

### ISSUE THREAD

**Issue by Ciantic** [matiwinnetou/swagger-play24#3]
I know this is not specifically about this, but I was wondering do you know what is minimal amount of Annotation required with Play2.4?

Ideally it should be able to guess the request type (GET,POST) and Url from routes file, only thing I should give is summary, but it doesn't work if I only annotate `@ApiOperation` to my controller action.

**Comment by laguiz** [comment]
+1

**Comment by matiwinnetou** [comment]
No that is not supported. That would be an awesome feature but I would say wordnik implemented a somewhat rudimentary support for Play 2.3.x, my contribution is just porting this to Play 2.4

**Comment by cdparra** [comment]
Just tested on a play2.4 app, with endpoints being annotated with @ApiOperation. The module only generates documentation for @Api annotations, but not with the included @ApiOperation in each controller.

**Comment by michalzubkowicz** [comment]
why you did not push it to main?

**Comment by matiwinnetou** [comment]
because they don't want play 2.4 support in swagger-core anymore + I don't have access to their repo.

**Comment by cdparra** [comment]
Forget about my previous comment, it is working fine.

**Comment by Ciantic** [comment]
@matiwinnetou you know they are moving the scala support to here: https://github.com/swagger-api/swagger-scala-module maybe the effort should be to improve that?

**Comment by matiwinnetou** [comment]
I am aware of that but it may also be a kitchen sink. Do you want to support scalatra and play in the same repository?
