### ISSUE TITLE
Error running tests 

### ISSUE THREAD

**Issue by pedrolopix** [matiwinnetou/swagger-play24#9]
[info] application - Creating Pool for datasource 'default'
[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[warn] swagger - ControllerScanner - looking for controllers with API annotation
com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in play.modules.swagger.SwaggerPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at play.modules.swagger.SwaggerPlugin.class(SwaggerPlugin.scala:26)
  while locating play.modules.swagger.SwaggerPlugin

the test code is:

public class AcessoTest {

```
@Test
public void testFooRoute() {
    running(testServer(3333, fakeApplication(inMemoryDatabase())), HTMLUNIT, browser -> {
        browser.goTo("http://localhost:3333/api/v1/loginurl");
        assertTrue(browser.pageSource().contains("Your new application is ready."));
    });
}
```

}

Any Ideias?

**Comment by matiwinnetou** [comment]
Not sure what this is but I would disable swagger in such an integration test. You can find a way to disable play modules in the official 2.4 docu
